bookflood/urls.py
from django.conf.urls import url
from django.contrib import admin 
#from bookflood.views import home, view_book, view_person
from bookflood import views

urlpatterns = [
    url(r'^$', views.PeopleList.as_view(), name='home'), 
    url(r'^books/$', views.BookList.as_view(), name='books'),
    url(r'^books/add/$', views.BookCreate.as_view(), name='addbook'),
    url(r'^books/(?P<pk>\d+)/$', views.BookDetail.as_view(), name='bookdetail'),
    #url(r'^person/$', view_person, name='person'),

]

django_bookflood/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('bookflood.urls')),

]

bookflood/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Country(models.Model):
    name = models.CharField(max_length=100)
    class Meta(object):
        verbose_name_plural='countries'
    def __str__(self):
        return self.name
class Genre(models.Model): 
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
class Language(models.Model): 
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
class Book(models.Model): 
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    isbn = models.IntegerField(
            blank = True,
            null = True,
            )
    price = models.DecimalField(
            max_digits=8,
            decimal_places=2,
            blank = True,
            null = True,
            )
    date_published = models.DateField(
            blank = True,
            null = True,
            )
    language = models.ForeignKey(Language, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    def get_absolute_url(self): 
        return reverse('bookdetail', kwargs={'pk':self.id})

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField()
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    books_read = models.ManyToManyField(Book, related_name='read_it')
    books_wanted = models.ManyToManyField(Book, related_name='want_it')
    languages = models.ManyToManyField(Language)
    genres = models.ManyToManyField(Genre)

    def __str__(self):
        return self.user.get_full_name()

bookflood/views.py
from django.shortcuts import render
from django.views.generic import View, DetailView, ListView
from django.views.generic.edit import CreateView
from bookflood.models import UserProfile, Book

class BookView(View): 
    model=Book

class BookCreate(BookView, CreateView): 
    fields=['title', 'author', 'isbn', 'genre', 'language']

class BookList(BookView, ListView): 
    template_name='book.html'

class PeopleList(ListView): 
    model=UserProfile
    template_name='home.html'

class BookDetail(BookView, DetailView): 
    pass
    model=Book
    

def home(request):
   user_profiles = UserProfile.objects.all()
   data = { 'people': user_profiles
           }
   return render(request, 'home.html', data)

def view_person(request): 
    person = UserProfile.objects.get(id=1)
    data = {'person' : person} 
    return render(request, 'person.html', data)

def view_book(request): 
    books = Book.objects.all()
    data = {'books': books} 
    return render(request, 'book.html', data)

bookflood/templates/base.html
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./../../static/main.css">
	</head>
	<body>

		<div class="topnav">
			<a href={% url 'home' %}>Home</a>
			<a href={% url 'book' %}>Books</a>
		</div>

		{% block content %} 
		{% endblock %} 

        </body>

</html>

bookflood/templates/book.html
{% extends 'base.html' %}
{% block content %}
{{book_list}} 
<br></br>
{% for book in book_list %}
<a href="{% url 'bookdetail' pk=book.id %}">{{book.title}}
	<br></br>
	{{book.author}}</a>
<br></br>
{% endfor %} 
<a href="{% url 'addbook' %}" >Add Book</a>

{% endblock %}

bookflood/templates/bookflood/book_detail.html
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./../../static/main.css">
	</head>
	<body>

		<div class="topnav">
			<a href={% url 'home' %}>Home</a>
			<a href={% url 'book' %}>Books</a>
		</div>

		<p> All Books </p>
		{{book.name}} 
		{{book.title}} 
		{{book.author}} 
	</body>

</html>

bookflood/templates/bookflood/book_form.html
{% extends 'base.html' %}
{% block content %} 
<form action="" method="POST">
{% csrf_token %}
{{form.as_p}} 
<input type="Submit">
{% endblock %}  
</form>

bookflood/templates/home.html
<html>
	<head>
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"/>
	</head>
	<!--transfer to external css later! -->
	<body>
		<div class= "page-header">
			<h1> Welcome to Bookflood! </h1>
		</div>
		<h2>
			Jolabokaflod, the Icelandic word for ''Christmas Book Flood,'' describes the Iceland's national culture of gifting books as presents on December 24th, and then spending the night reading. Inspired by the decades-long tradition, America is starting its own Christmas Book Flood, starting from here. With Book Flood, you can create a profile, connect with friends, let others know which books you've read and you like, what books your friends and you have read and liked, and what books you should consider buying for a newfound American tradition of a flourishing literary adventure. Welcome to Book Flood.

		</h2>
		 <div class="topnav">
			 <a href={% url 'home' %}>Home</a>
			 <a href={% url 'book' %}>Books</a>
                </div>

		<div class= "page contents"> 
		<!--{{people}}-->
		{% for person in people %} 
		{{person}}
		{% endfor %}
		</div>
	</body>

</html>

bookflood/templates/person.html
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./../../static/main.css">
	</head>
	<div class="topnav">
		<a href={% url 'home' %}>Home</a>
		<a href={% url 'book' %}>Books</a>
	</div>
	<body>
		<p> Your profile </p>
		{{person}}
	</body>

</html>